# general
gpu_id: 0
use_gpu: True
seed: 2021
state: INFO
reproducibility: False
data_path: 'data/'
checkpoint_dir: 'saved/'
generated_text_dir: 'generated/'
plot: True

# training settings
epochs: 30
warmup_epochs: 0
iters_per_epoch: 1000
train_batch_size: 64
learner: schedule
learning_rate: 0.001
eval_step: 1
stopping_step: 3
grad_clip: 1.0

# evaluation settings
eval_batch_size: 32

