#!/bin/bash
#SBATCH --job-name=copynopgen0to30
#SBATCH --account=wj84
#SBATCH --time=15:00:00
#SBATCH --ntasks=1
#SBATCH --mem=16G
#SBATCH --cpus-per-task=4
#SBATCH --gres=gpu:V100:1
#SBATCH --partition=m3g
#SBATCH --constraint=V100-32G

module load cuda/10.2

python fire.py
